
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { CustomProvider } from "rsuite";
import "rsuite/dist/rsuite-no-reset.min.css";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Forum Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={geistMono.style}
        className={`antialiased `}
      >
        <CustomProvider>
          <Navbar />
          <main className="min-h-[40vh] flex flex-col">
            {children}
          </main>
          <Footer />
        </CustomProvider>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
