
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "rsuite/dist/rsuite-no-reset.min.css";
import "./globals.css";


export const metadata: Metadata = {
  title: "Forum Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased mb-[80px] md:mb-0`}
      >
        <Navbar />
        <main className="min-h-[40vh] flex flex-col">
          {children}
        </main>
        <Footer />
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
